### ISSUE TITLE
Webpack build error when importing Card component.

### ISSUE THREAD

**Issue by lucasmullerm** [grommet/grommet#1018]
### Expected Behavior

Importing Card Component.
### Actual Behavior

Build Error:

```
    ERROR in ./~/character-entities-legacy/index.json
    Module parse failed: W:\atlassocial\node_modules\character-entities-legacy\index.json Unexpected token (2:9)
    You may need an appropriate loader to handle this file type.
    SyntaxError: Unexpected token (2:9)
        at Parser.pp$4.raise (W:\atlassocial\node_modules\acorn\dist\acorn.js:2221:15)
        at Parser.pp.unexpected (W:\atlassocial\node_modules\acorn\dist\acorn.js:603:10)
        at Parser.pp.semicolon (W:\atlassocial\node_modules\acorn\dist\acorn.js:581:61)
        at Parser.pp$1.parseExpressionStatement (W:\atlassocial\node_modules\acorn\dist\acorn.js:966:10)
        at Parser.pp$1.parseStatement (W:\atlassocial\node_modules\acorn\dist\acorn.js:730:24)
        at Parser.pp$1.parseBlock (W:\atlassocial\node_modules\acorn\dist\acorn.js:981:25)
        at Parser.pp$1.parseStatement (W:\atlassocial\node_modules\acorn\dist\acorn.js:709:33)
        at Parser.pp$1.parseTopLevel (W:\atlassocial\node_modules\acorn\dist\acorn.js:638:25)
        at Parser.parse (W:\atlassocial\node_modules\acorn\dist\acorn.js:516:17)
        at Object.parse (W:\atlassocial\node_modules\acorn\dist\acorn.js:3098:39)
        at Parser.parse (W:\atlassocial\node_modules\webpack\lib\Parser.js:902:15)
        at DependenciesBlock.<anonymous> (W:\atlassocial\node_modules\webpack\lib\NormalModule.js:104:16)
        at DependenciesBlock.onModuleBuild (W:\atlassocial\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
        at nextLoader (W:\atlassocial\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
        at W:\atlassocial\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
        at Storage.finished (W:\atlassocial\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
     @ ./~/character-entities-legacy/index.js 12:17-40

    ERROR in ./~/character-reference-invalid/index.json
    Module parse failed: W:\atlassocial\node_modules\character-reference-invalid\index.json Unexpected token (2:5)
    You may need an appropriate loader to handle this file type.
    SyntaxError: Unexpected token (2:5)
        at Parser.pp$4.raise (W:\atlassocial\node_modules\acorn\dist\acorn.js:2221:15)
        at Parser.pp.unexpected (W:\atlassocial\node_modules\acorn\dist\acorn.js:603:10)
        at Parser.pp.semicolon (W:\atlassocial\node_modules\acorn\dist\acorn.js:581:61)
        at Parser.pp$1.parseExpressionStatement (W:\atlassocial\node_modules\acorn\dist\acorn.js:966:10)
        at Parser.pp$1.parseStatement (W:\atlassocial\node_modules\acorn\dist\acorn.js:730:24)
        at Parser.pp$1.parseBlock (W:\atlassocial\node_modules\acorn\dist\acorn.js:981:25)
        at Parser.pp$1.parseStatement (W:\atlassocial\node_modules\acorn\dist\acorn.js:709:33)
        at Parser.pp$1.parseTopLevel (W:\atlassocial\node_modules\acorn\dist\acorn.js:638:25)
        at Parser.parse (W:\atlassocial\node_modules\acorn\dist\acorn.js:516:17)
        at Object.parse (W:\atlassocial\node_modules\acorn\dist\acorn.js:3098:39)
        at Parser.parse (W:\atlassocial\node_modules\webpack\lib\Parser.js:902:15)
        at DependenciesBlock.<anonymous> (W:\atlassocial\node_modules\webpack\lib\NormalModule.js:104:16)
        at DependenciesBlock.onModuleBuild (W:\atlassocial\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
        at nextLoader (W:\atlassocial\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
        at W:\atlassocial\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
        at Storage.finished (W:\atlassocial\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
     @ ./~/character-reference-invalid/index.js 12:17-40

    ERROR in ./~/character-entities/index.json
    Module parse failed: W:\atlassocial\node_modules\character-entities\index.json Unexpected token (2:8)
    You may need an appropriate loader to handle this file type.
    SyntaxError: Unexpected token (2:8)
        at Parser.pp$4.raise (W:\atlassocial\node_modules\acorn\dist\acorn.js:2221:15)
        at Parser.pp.unexpected (W:\atlassocial\node_modules\acorn\dist\acorn.js:603:10)
        at Parser.pp.semicolon (W:\atlassocial\node_modules\acorn\dist\acorn.js:581:61)
        at Parser.pp$1.parseExpressionStatement (W:\atlassocial\node_modules\acorn\dist\acorn.js:966:10)
        at Parser.pp$1.parseStatement (W:\atlassocial\node_modules\acorn\dist\acorn.js:730:24)
        at Parser.pp$1.parseBlock (W:\atlassocial\node_modules\acorn\dist\acorn.js:981:25)
        at Parser.pp$1.parseStatement (W:\atlassocial\node_modules\acorn\dist\acorn.js:709:33)
        at Parser.pp$1.parseTopLevel (W:\atlassocial\node_modules\acorn\dist\acorn.js:638:25)
        at Parser.parse (W:\atlassocial\node_modules\acorn\dist\acorn.js:516:17)
        at Object.parse (W:\atlassocial\node_modules\acorn\dist\acorn.js:3098:39)
        at Parser.parse (W:\atlassocial\node_modules\webpack\lib\Parser.js:902:15)
        at DependenciesBlock.<anonymous> (W:\atlassocial\node_modules\webpack\lib\NormalModule.js:104:16)
        at DependenciesBlock.onModuleBuild (W:\atlassocial\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
        at nextLoader (W:\atlassocial\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
        at W:\atlassocial\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
        at Storage.finished (W:\atlassocial\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
     @ ./~/character-entities/index.js 12:17-40
```

### Steps to Reproduce

`import Card from 'grommet/components/Card'`
### Your Environment

- Grommet version: 0.6.11
- Node version: 6.5.0
- Npm version: 3.10.3
- Operating System: Windows 10

**Comment by alansouzati** [comment]
Interesting. can you update to Grommet 1.0.0 and see if you are able to reproduce this?!

**Comment by lucasmullerm** [comment]
updating to 1.0.0 I got the same erros plus this one:

```
ERROR in ./~/remark-parse/lib/defaults.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./block-elements in W:\atlassocial\node_modules\remark-parse\lib
 @ ./~/remark-parse/lib/defaults.js 19:10-37
```

**Comment by alansouzati** [comment]
Are you using grommet-toolbox or do you have your own webpack configuration?

**Comment by lucasmullerm** [comment]
My own configuration. I was missing a json loader, that's the reason for the 3 first erros. But I still trying to figure this last error, `block-elements` is also a json file.

**Comment by alansouzati** [comment]
Yeah, we add json-loader as part of the toolbox, but I was not aware of this requirement, and I still cannot reproduce it using the grommet-standalone: https://github.com/grommet/grommet-standalone.

Would you mind to give it a try and see if you can reproduce it there?

If you check the webpack configuration, there is no json-loader in the grommet-standalone instance.

**Comment by alansouzati** [comment]
what is your webpack version?

**Comment by alansouzati** [comment]
Grommet-standalone uses "webpack": "^1.13.1"

**Comment by lucasmullerm** [comment]
I got the same 4 errors in grommet-standalone. And after using the json-loader I still got the last error. I use webpack 1.13.2.

**Comment by lucasmullerm** [comment]
```
ERROR in ./~/remark-parse/lib/defaults.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./block-elements in W:\atlassocial\node_modules\remark-parse\lib
 @ ./~/remark-parse/lib/defaults.js 19:10-37
```

this errorr is fixed if I change the module code from `require('./block-elements')` to `require('./block-elements.json')`.
Any ideas why?

**Comment by alansouzati** [comment]
I have a windows VM, let me try and see if I can reproduce it there. There is something weird going on. I'm not sure why you would have to put this `require('./block-elements.json')`.

Do you have a Linux Vm somewhere? Can you try to see if you can reproduce in a different OS?

**Comment by lucasmullerm** [comment]
I am trying now on a linux VM. Do I have to install any extra global module to use the webpack config file in es6?

**Comment by alansouzati** [comment]
you will need a .babelrc file in the root of your project:

https://github.com/grommet/grommet-standalone/blob/master/.babelrc

**Comment by lucasmullerm** [comment]
The .babelrc file already exists because of the git clone, but I still get syntax error.

**Comment by lucasmullerm** [comment]
I reproduced it in a Linux VM. Dit not have any issues. No need for a json loader.

**Comment by alansouzati** [comment]
I've just ran grommet-standalone with a Windows box and I still cannot reproduce the issue.

![screen shot 2016-10-28 at 11 00 50 am](https://cloud.githubusercontent.com/assets/1207250/19816849/d23b4976-9cfd-11e6-9890-e95497d17456.png)

**Comment by lucasmullerm** [comment]
It looks like mine is not looking for .json on require. It only works when importing the Card component. The original grommet-standalone builds.

![image](https://cloud.githubusercontent.com/assets/4108952/19834626/2564769e-9e4e-11e6-900f-b2eb96cbcdf2.png)

**Comment by bnoguchi** [comment]
@lucasmullerm In your webpack config, just make sure to add a ".json" to your resolve extensions:

```
resolve: {
    root: path.resolve('./mydir'),
    extensions: ['', '.js', '.json'] // <- Just append a '.json' here
  }
```

**Comment by lucasmullerm** [comment]
Thanks.

**Comment by nomadus** [comment]
If the above did not fix, add the following to fix issue
loaders: [
            { test: /\.json$/, loader: "json-loader" }
        ]
