### ISSUE TITLE
Timestamp component: Deprecation warning: moment().lang() is deprecated. Instead, use moment().localeData() to get the language configuration. Use moment().locale() to change languages.

### ISSUE THREAD

**Issue by ezzatron** [grommet/grommet#1376]
This deprecation warning has started to display when using the `Timestamp` component after a recent update:

```
Deprecation warning: moment().lang() is deprecated. Instead, use moment().localeData() to get the language configuration. Use moment().locale() to change languages.
Arguments: en-AU
Error
    at Moment.lang (http://localhost:8080/js/app.js:592:94)
    at Timestamp._formatForLocale (http://localhost:8080/js/app.js:36451:78)
    at Timestamp.componentDidMount (http://localhost:8080/js/app.js:36437:12)
    at http://localhost:8080/js/app.js:93504:25
    at measureLifeCyclePerf (http://localhost:8080/js/app.js:93314:12)
    at http://localhost:8080/js/app.js:93503:11
    at CallbackQueue.notifyAll (http://localhost:8080/js/app.js:50937:22)
    at ReactReconcileTransaction.close (http://localhost:8080/js/app.js:98414:26)
    at ReactReconcileTransaction.closeAll (http://localhost:8080/js/app.js:26093:25)
    at ReactReconcileTransaction.perform (http://localhost:8080/js/app.js:26040:16)
```

**Comment by alansouzati** [comment]
This is actually fixed in the master branch and it will be part of the next grommet release.

https://github.com/grommet/grommet/blob/master/src/js/components/Timestamp.js#L42

Thanks for reporting this.
