### ISSUE TITLE
Weird issue installing

### ISSUE THREAD

**Issue by cristiandley** [grommet/grommet#1712]
Yarn/Npm asking for a "node-emoji" module ?

### Expected Behavior

- Install Grommet NPM package

### Actual Behavior

```
Exit code: 1
Command: node ./tools/warn-alpha
Arguments: 
Directory: /home/cristian/Proyectos/test/node_modules/grommet
Output:
module.js:471
    throw err;
    ^

Error: Cannot find module 'node-emoji'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/cristian/Proyectos/haciendolio/node_modules/grommet/tools/warn-alpha.js:1:77)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

### Steps 
 1. `yarn add grommet` | `npm i -g grommet`
 2. :fire: 
 3. :boom: 

### Env
* Grommet version: 1.3.2
* Operating System and version (desktop or mobile): Ubuntu 17

If i add `node-emoji` everything works cool

**Comment by vojtasvoboda** [comment]
Same here. I fixed this by running `yarn add node-emoji; yarn add grommet`.

**Comment by alansouzati** [comment]
Fixed by this [commit](https://github.com/grommet/grommet/commit/4c3ab266e969f9973bf44317897091c64d77aa26)

Thanks for reporting this.
