### ISSUE TITLE
Table not testable with selectable prop

### ISSUE THREAD

**Issue by jozsi** [grommet/grommet#1806]
Snapshot testing fails via `jest`/`react-test-renderer` when the `selectable` prop is set on a `Table`.

### Expected Behavior
Should create test snapshot.

### Actual Behavior
```
    TypeError: element.getAttribute is not a function
      
      at generateId (node_modules/grommet/utils/DOM.js:125:29)
      at Object._initKeyboardAccelerators (node_modules/grommet/utils/KeyboardAccelerators.js:54:34)
      at Object.startListeningToKeyboard (node_modules/grommet/utils/KeyboardAccelerators.js:94:12)
      at Table.componentDidMount (node_modules/grommet/components/Table.js:190:40)
      at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4553:24)
```

### URL, screen shot, or Codepen exhibiting the issue
https://github.com/jozsi/grommet-test-bug/blob/master/src/Table.test.js

### Steps to Reproduce
 1.  git clone git@github.com:jozsi/grommet-test-bug.git
 2. yarn install
 3. yarn run reproduce

### Your Environment
* Grommet version: latest (1.10.0)

**Comment by jozsi** [comment]
PR with fix done: #1808 - thanks @atanasster !
