### ISSUE TITLE
NEXT and node version 9 required

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#1834]
Running the v2 (branch NEXT) tests fails on node v 7.4
### Expected Behavior
Support node v7 or make node v9 a requirement in package.json ( `https://docs.npmjs.com/files/package.json#engines` )
### Actual Behavior
The following error running tests:
```
FAIL  src/js/components/Responsive/__tests__/Responsive-test.js
  ● Responsive renders

    expect(jest.fn()).toBeCalledWith(expected)
    
    Expected mock function to have been called with:
      ["narrow"]
    But it was called with:
      ["wide"]
      
      at Object.<anonymous> (src/js/components/Responsive/__tests__/Responsive-test.js:23:20)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
      at process._tickCallback (internal/process/next_tick.js:103:7)
```
### Steps to Reproduce
Install node v 7.4
```
git clone -b NEXT https://github.com/grommet/grommet.git
npm install
npm run test-update
```

**Comment by ericsoderberghp** [comment]
Take a look. But, not necessarily delay v2.0.0 for this.
