### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'colors' of undefined

### ISSUE THREAD

**Issue by kanonochina** [grommet/grommet#2589]
Whenever I use a component that has something to do with colors I get an error

```bash
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'colors' of undefined
```

from 
`<Box`   __background='dark-4'__ ` align='center' justify='center' pad='large'>`

```html
<Stack anchor='center'>
    <Box background='dark-4' align='center' justify='center' pad='large'>
        <Paragraph>
            {`You know, sometimes in life it seems like there's no way out. Like
                a sheep trapped in a maze designed by wolves.`}
        </Paragraph>
    </Box>
    <Box
        pad='large'
        round='small'
    >
        <Text size='large'><strong>Hey!</strong></Text>
    </Box>
</Stack>
````

Error from terminal

```bash
(node:18048) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'colors' of undefined
    at normalizeColor (/Users/station/nodesandbox/Project/node_modules/grommet/utils/colors.js:8:32)
    at backgroundIsDark (/Users/station/nodesandbox/Project/node_modules/grommet/utils/background.js:52:47)
    at BoxImpl.render (/Users/station/nodesandbox/Project/node_modules/grommet/components/Box/Box.js:104:46)
    at processChild (/Users/station/nodesandbox/Project/node_modules/react-dom/cjs/react-dom-server.node.development.js:2207:18)
    at resolve (/Users/station/nodesandbox/Project/node_modules/react-dom/cjs/react-dom-server.node.development.js:2064:5)
    at ReactDOMServerRenderer.render (/Users/station/nodesandbox/Project/node_modules/react-dom/cjs/react-dom-server.node.development.js:2383:22)
    at ReactDOMServerRenderer.read (/Users/station/nodesandbox/Project/node_modules/react-dom/cjs/react-dom-server.node.development.js:2357:19)
    at Object.renderToString (/Users/station/nodesandbox/Project/node_modules/react-dom/cjs/react-dom-server.node.development.js:2729:25)
    at eval (webpack:///./server.js?:286:40)
```

### Your Environment

- Grommet version: 2.2.1
- Browser Name and version: Chrome Version 70
- Operating System and version (desktop or mobile): MacOS Mojave

**Comment by oorestisime** [comment]
hello,
are you using a custom theme? did you maybe forget to include colors in the theme or merge your modifications with the base theme?
generally it is a bit difficult to debug here, a codesandbox or a link to a repo illustrating the problem could certainly help

**Comment by alansouzati** [comment]
make sure you are using grommet-icons v4. with grommet 2.2.1

**Comment by ShimiSun** [comment]
hi @kanonochina, is the issue still reproducible after applying the suggested changes on top?

**Comment by kanonochina** [comment]
Hi @ShimiSun The updated package.json fixed the issue, Thanks for the help

**Comment by ShimiSun** [comment]
@kanonochina glad to hear 👍
