### ISSUE TITLE
Parcel's tree-shaking breaks when using Grommet

### ISSUE THREAD

**Issue by milanvdm** [grommet/grommet#3021]
I made a simple repo to reproduce this behaviour: https://github.com/milanvdm/parcel-grommet

When you run `yarn run build` which is set to `parcel build ./public/index.html --experimental-scope-hoisting` it will throw the following exception:

```
../node_modules/styled-components/dist/styled-components.browser.esm.js does not export 'ThemeContext'
    at replaceExportNode (/Users/milanvandermeer/dev/projects/parcel-grommet/node_modules/parcel-bundler/src/scope-hoisting/concat.js:54:13)
    at ReferencedIdentifier (/Users/milanvandermeer/dev/projects/parcel-grommet/node_modules/parcel-bundler/src/scope-hoisting/concat.js:317:20)
    at newFn (/Users/milanvandermeer/dev/projects/parcel-grommet/node_modules/parcel-bundler/node_modules/@babel/traverse/lib/visitors.js:230:17)
    at NodePath._call (/Users/milanvandermeer/dev/projects/parcel-grommet/node_modules/parcel-bundler/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/milanvandermeer/dev/projects/parcel-grommet/node_modules/parcel-bundler/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/milanvandermeer/dev/projects/parcel-grommet/node_modules/parcel-bundler/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/Users/milanvandermeer/dev/projects/parcel-grommet/node_modules/parcel-bundler/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/Users/milanvandermeer/dev/projects/parcel-grommet/node_modules/parcel-bundler/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/Users/milanvandermeer/dev/projects/parcel-grommet/node_modules/parcel-bundler/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/Users/milanvandermeer/dev/projects/parcel-grommet/node_modules/parcel-bundler/node_modules/@babel/traverse/lib/index.js:94:17)
error Command failed with exit code 1.
```

**Comment by ShimiSun** [comment]
Thanks for taking the time to file the issue. The error isn't pointing at grommet itself, and it is not reproducible on other Parcel+Grommet apps I've tested with, hence I suspect it is specific to your local repo.
See for example https://github.com/ShimiSun/grommet-parcel-app, the project is running Parcel + Grommet + tree-shaking and it works as expected. 
Let me know if you are able to isolate the error to a more minimal code.

build results with tree-shaking
```
➜  grommet-parcel-app git:(master) ✗ yarn build
yarn run v1.15.2
$ parcel build index.html --experimental-scope-hoisting
✨  Built in 21.10s.

dist/src.8c92368f.js     245.3 KB    20.24s
dist/index.html             296 B     3.84s
dist/src.91f4785a.css       145 B     9.14s
✨  Done in 22.21s.
```

**Comment by milanvdm** [comment]
Thanks for looking into this!

It seems that after some fiddling around, it seems that my `tsconfig` file for reason is causing this error message.

I'll close this issue as it is as you said, not related to Grommet :)
