### ISSUE TITLE
Cannot read property 'extend' of undefined" with Next.js and React Testing Library

### ISSUE THREAD

**Issue by mmnoo** [grommet/grommet#3638]
### Expected Behavior

Tests that test components that include Grommet's `<FormField />` component run without errors. 

### Actual Behavior
simple test fails with console output:
```
 TypeError: Cannot read property 'extend' of undefined

       6 | 
       7 | test('test' ,() => {
    >  8 |   const { getByText, getByRole } = render(<App />)
         |                                    ^
       9 | })
      10 | 

      at node_modules/grommet/components/FormField/FormField.js:66:32
      at Object.<anonymous> (components/App.spec.js:8:36)
```

### URL, screen shot, or Codepen exhibiting the issue

https://github.com/mmnoo/grommet-formfield-causing-test-error

### Steps to Reproduce

1. clone above repo
2. run `npm install`.
3. run `npm run test`.
4. notice error in test console.

### Your Environment

- Grommet version: 2.9.0
- Browser Name and version: integration test (React Testing Library)
- Operating System and version macOS 10.15.2

**Comment by mmnoo** [comment]
OK, I was mixing up a bunch of similar errors. For anyone who stumbles upon this closed issue, it is solved by wrapping the component being tested in a`<Grommet theme={theme}>` (like is necessary to make Grommet work in your app). 

I solved another seemingly similar issue by cleaning up the `moduleDirectories` property in `jest.config.js`.
