### ISSUE TITLE
Warning when rendering application using SSR frameworks like 'Razzle'

### ISSUE THREAD

**Issue by hitesh97** [grommet/grommet#4765]
When I started to put simple application page together with Server Side Rendering React based boilerplate project ( razzle )

it gives me following error

Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://fb.me/react-uselayouteffect-ssr for common fixes.

### Expected Behavior

expected that components will handle these for server side rendered applications

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by cmraible** [comment]
I'm seeing the same warning when using the grommet "stable" (master) branch and NextJS for Server Side Rendering.

### Expected behavior
No warnings for server side rendering.

### Actual Behavior

The issue appears to be with the usage of useLayoutEffect with any Server Side Rendering framework. In my case, the warning appears when I use the DataTable component, which uses InfiniteScroll, which in turn uses useLayoutEffect.

Just confirmed that I only see the warning when using the master branch. It does not appear when using the current npm package (2.15.2).

useLayoutEffect appears to have been introduced to InfiniteScroll at [0f32643](https://github.com/grommet/grommet/commit/0f32643d40fe0d654628550b3252486225b41100#diff-6354c32a84867b01ce050c35160e79030204f0ea9c8687bd5ebec70687115171)

```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at InfiniteScroll (.../node_modules/grommet/components/InfiniteScroll/InfiniteScroll.js:17:23)
    at tbody
    at StyledTable__StyledTableBody (.../node_modules/styled-components/dist/styled-components.cjs.js:1:18828)
    at TableBody
    at StyledDataTable__StyledDataTableBody (.../node_modules/styled-components/dist/styled-components.cjs.js:1:18828)
    at Keyboard (.../node_modules/grommet/components/Keyboard/Keyboard.js:25:21)
    at .../node_modules/grommet/components/DataTable/Body.js:33:25
    at table
    at StyledTable (.../node_modules/styled-components/dist/styled-components.cjs.js:1:18828)
    at Table (.../node_modules/grommet/components/Table/Table.js:15:22)
    at StyledDataTable (.../node_modules/styled-components/dist/styled-components.cjs.js:1:18828)
    at DataTable (.../node_modules/grommet/components/DataTable/DataTable.js:54:25)
    at div
    at StyledBox (.../node_modules/styled-components/dist/styled-components.cjs.js:1:18828)
    at Box (.../node_modules/grommet/components/Box/Box.js:27:24)
    at Home (webpack-internal:///./pages/index.js:25:61)
    at div
    at StyledGrommet (.../node_modules/styled-components/dist/styled-components.cjs.js:1:18828)
    at Grommet (.../node_modules/grommet/components/Grommet/Grommet.js:56:29)
    at MyApp (webpack-internal:///./pages/_app.js:21:3)
    at AppContainer (.../node_modules/next/dist/next-server/server/render.js:23:748)
```

### Steps to reproduce
1. Create a new Next.js project: `npx create-next-app`
2. Use the DataTable Component 

### Your environment
Grommet version: 'stable'
Browser: Chrome 87
OS: macOS catalina


Potential solution, albeit a bit hacky: https://medium.com/@alexandereardon/uselayouteffect-and-ssr-192986cdcf7a

**Comment by ShimiSun** [comment]
Thank you guys for the feedback, sounds like you have an overall idea of how to approach the issue, feel free to make an open-source contribution to help other SSR fellows. 
BTW, attaching a link to the official React issue https://github.com/facebook/react/issues/14363
And also to confirm, you guys are not seeing the warning on production, correct?

**Comment by hitesh97** [comment]
Hi team,

I was seeing this issue on Layer component as well as other components on
the latest package from npm, which I believe is the production version.

Whilst we know the workaround, being delaying the rendering of these
component until dom is available,  I.e. wrap the rendering of these
components in 'useEffect' hook.

It would be great if all components wldid that within their own code.
That will make all components SSR compliant and avoid these warnings.

Hope that helps.

Regards
Hitesh.
