### ISSUE TITLE
Couldn't find preset "es2015" relative to directory (getting started)

### ISSUE THREAD

**Issue by dfischer** [grommet/grommet#477]
I get this error when following the getting started guide:

```
 [75] (webpack)/hot/log-apply-result.js 813 bytes {0} [built]

ERROR in ./src/js/index.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/Users/DFischer/Code/os/grommet/sample-app"
    at /Users/DFischer/Code/os/grommet/sample-app/node_modules/grommet/node_modules/babel-core/lib/transformation/file/options/option-manager.js:372:17
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/DFischer/Code/os/grommet/sample-app/node_modules/grommet/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)
    at OptionManager.mergePresets (/Users/DFischer/Code/os/grommet/sample-app/node_modules/grommet/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)
    at OptionManager.mergeOptions (/Users/DFischer/Code/os/grommet/sample-app/node_modules/grommet/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)
    at OptionManager.addConfig (/Users/DFischer/Code/os/grommet/sample-app/node_modules/grommet/node_modules/babel-core/lib/transformation/file/options/option-manager.js:207:10)
    at OptionManager.findConfigs (/Users/DFischer/Code/os/grommet/sample-app/node_modules/grommet/node_modules/babel-core/lib/transformation/file/options/option-manager.js:413:16)
    at OptionManager.init (/Users/DFischer/Code/os/grommet/sample-app/node_modules/grommet/node_modules/babel-core/lib/transformation/file/options/option-manager.js:461:12)
    at File.initOptions (/Users/DFischer/Code/os/grommet/sample-app/node_modules/grommet/node_modules/babel-core/lib/transformation/file/index.js:194:75)
    at new File (/Users/DFischer/Code/os/grommet/sample-app/node_modules/grommet/node_modules/babel-core/lib/transformation/file/index.js:123:22)
    at Pipeline.transform (/Users/DFischer/Code/os/grommet/sample-app/node_modules/grommet/node_modules/babel-core/lib/transformation/pipeline.js:45:16)
    at transpile (/Users/DFischer/Code/os/grommet/sample-app/node_modules/grommet/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (/Users/DFischer/Code/os/grommet/sample-app/node_modules/grommet/node_modules/babel-loader/index.js:88:12)
 @ multi app
webpack: bundle is now VALID.
```

**Comment by dfischer** [comment]
Update: I fixed this error by doing:

```
npm install babel-preset-es2015 --save --no-bin-links
npm install babel-preset-react --save --no-bin-links
```

But I feel like grommet should already take care of these pre-req?

**Comment by alansouzati** [comment]
yeah we should, can you confirm your NPM and Node versions?

I'm assuming you have NPM < 3 where the dependencies are nested. 

Starting from NPM 3+ dependencies are flat, so you will not face this issue.

There are other reasons that are leading us to update our supported NPM + Node distributions.

In the meantime, I agree with you that Grommet should add both `babel-preset-es2015` and `babel-preset-react` to the `package.json` of the init app.

Thanks for your feedback :+1:

**Comment by dfischer** [comment]
```
npm --version
2.14.6

node --version
v4.1.2
```

No problem. Thanks 👍
