### ISSUE TITLE
#stable branch isn't being published

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/grommet#5417]
The grommet #stable branch automatic publishing is broken.

https://app.circleci.com/pipelines/github/grommet/grommet/9049/workflows/feed23d3-d388-45b5-bd6d-046a6ab0089f/jobs/44633

```
simple-git [GitExecutor]  Failed GitError: Pushing to https://****************************************@github.com/grommet/grommet.git remote: You must verify your email address. remote: See https://github.com/settings/emails. fatal: unable to access 'https://****************************************@github.com/grommet/grommet.git/': The requested URL returned error: 403  at Object.action (/home/circleci/grommet-ci/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:38:28) at PluginStore.exec (/home/circleci/grommet-ci/node_modules/simple-git/src/lib/plugins/plugin-store.ts:24:29) at /home/circleci/grommet-ci/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:114:40 at new Promise (<anonymous>) at GitExecutorChain.handleTaskData (/home/circleci/grommet-ci/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:111:14) at GitExecutorChain.<anonymous> (/home/circleci/grommet-ci/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:88:40) at Generator.next (<anonymous>) at fulfilled (/home/circleci/grommet-ci/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58) at runMicrotasks (<anonymous>)     at processTicksAndRejections (internal/process/task_queues.js:95:5) { task: { commands: [ 'push', 'origin', 'stable', '--verbose', '--porcelain' ], format: 'utf-8', parser: [Function: parsePushResult] } } +0ms
failed:  GitError: Pushing to https://****************************************@github.com/grommet/grommet.git
remote: You must verify your email address.
remote: See https://github.com/settings/emails.
fatal: unable to access 'https://****************************************@github.com/grommet/grommet.git/': The requested URL returned error: 403
```

The problem appears to be related to verifying the grommet@hpe.com email address with GitHub.

**Comment by MikeKingdom** [comment]
grommet@hpe.com is re-enabled and owned under me now. We still need to validate the release job works again in CircleCI

**Comment by MikeKingdom** [comment]
Verified with the grommet-theme-hpe release script which was failing the same way.
Failed one before the fix:
https://app.circleci.com/pipelines/github/grommet/grommet-theme-hpe/593/workflows/d0e2c160-e3b8-4a27-98b5-05ef9efd7dfe/jobs/1729

Successful one after the fix:
https://app.circleci.com/pipelines/github/grommet/grommet-theme-hpe/593/workflows/523c35e6-736b-443a-b156-8479184fe3ac/jobs/1735
