### ISSUE TITLE
failed to load external dependencies

### ISSUE THREAD

**Issue by ischyron** [grommet/grommet#563]
after a -g install! failed to load external dependencies ?

sudo npm install -g grommet
grommet init sample-app
gulp dev

can we do this with a babel.rc  ?

```
[22:21:44] Failed to load external module babel-register
[22:21:44] Failed to load external module babel-core/register
[22:21:44] Failed to load external module babel/register
/Users/ischyron/sample-app/gulpfile.babel.js:1
(function (exports, require, module, __filename, __dirname) { import gulp from 'gulp';
                                                              ^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:193:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)

```

**Comment by alansouzati** [comment]
can you confirm your node + npm version?

**Comment by ischyron** [comment]
sorry npm is v2 . closing this
