### ISSUE TITLE
Nextjs project trying to use Page component got a TypeError 

### ISSUE THREAD

**Issue by whisoer** [grommet/grommet#6055]
### Actual Behavior

```bash
TypeError: Cannot read properties of undefined (reading 'page')
    at /home/aquino/Repositorios/soc-analyzer/node_modules/grommet/components/Page/Page.js:38:44
    at Object.useMemo (/home/aquino/Repositorios/soc-analyzer/node_modules/react-dom/cjs/react-dom-server.browser.development.js:4961:19)
    at useMemo (/home/aquino/Repositorios/soc-analyzer/node_modules/react/cjs/react.development.js:1645:21)
    at Page (/home/aquino/Repositorios/soc-analyzer/node_modules/grommet/components/Page/Page.js:34:41)
    at renderWithHooks (/home/aquino/Repositorios/soc-analyzer/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5448:16)
    at renderIndeterminateComponent (/home/aquino/Repositorios/soc-analyzer/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5521:15)
    at renderElement (/home/aquino/Repositorios/soc-analyzer/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5736:7)
    at renderNodeDestructive (/home/aquino/Repositorios/soc-analyzer/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5875:11)
    at renderNode (/home/aquino/Repositorios/soc-analyzer/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6009:12)
    at renderChildrenArray (/home/aquino/Repositorios/soc-analyzer/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5965:7)
```

I got this error trying to use `Page` in my nextjs project. If I change Page to the `Main` component it works fine.
![image](https://user-images.githubusercontent.com/33878228/161995242-82c44485-2b6a-41af-876a-4067c0e350f9.png)

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version: ^2.22.0
- Next version: 12.1.4
- React version: 18.0.0
- Browser Name and version: Google Chrome Version 100.0.4896.60 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Ubuntu 20.04.4 LTS

**Comment by whisoer** [comment]
> It looks like the theme you're using doesn't have the new Page default styles. The base theme in grommet has Page styles and most themes should extend the base theme. What theme are you using?

Oh, that's it! I actually did not setup any theme. I just follow the installation process and start to use the components on my app.

Using `<Grommet>` around my entire app resolves! Thank you @MikeKingdom 

Would be nice to have this ThemeProvider configuration in a "usage" tutorial after the installation process.
