### ISSUE TITLE
release-stable is broken after upgrading 'del'

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/grommet#6258]
When we upgraded the `del` package to version 7, this broke the `release-stable` script, as the API for `del` changed. I think we need to change how we import it and use it.

The error reported by CircleCI is:

```
$ babel-node ./tools/release-stable
internal/modules/cjs/loader.js:1102
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/circleci/grommet-ci/node_modules/del/index.js
require() of ES modules is not supported.
require() of /home/circleci/grommet-ci/node_modules/del/index.js from /home/circleci/grommet-ci/tools/release-stable.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/circleci/grommet-ci/node_modules/del/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Object.newLoader [as .js] (/home/circleci/grommet-ci/node_modules/pirates/lib/index.js:141:7)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/home/circleci/grommet-ci/tools/release-stable.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/home/circleci/grommet-ci/node_modules/pirates/lib/index.js:136:24) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by ericsoderberghp** [comment]
Still having problems.
