### ISSUE TITLE
DataTableColumns component itself rendering ok but will crash the app after toggling a column or changing order of column

### ISSUE THREAD

**Issue by Lewiszhl** [grommet/grommet#6907]
### Expected Behavior
DataTableColumns can toggle the columns and switch the columns order

### Actual Behavior
After integrating with DataTableColumns to DataTable, the manageColumns button shows up correctly, and the menu of the columns options rendering correctly, but once the user clicks the checkbox in the menu or tries to switch any of the order of the columns, a compile error will be thrown out.

### URL, screen shot, or Codepen exhibiting the issue

<img width="1865" alt="Screen Shot 2023-07-26 at 12 47 33 PM" src="https://github.com/grommet/grommet/assets/73854746/d328294e-9eaf-42df-8a10-ca5fa36eeaa2">

<img width="1317" alt="Screen Shot 2023-07-26 at 12 48 55 PM" src="https://github.com/grommet/grommet/assets/73854746/f158c2ca-866b-4881-823c-75f5c3e8c0b9">

## Error
```
Compiled with problems:
×
ERROR
onView is not a function
TypeError: onView is not a function
    at http://localhost:3000/static/js/vendors-node_modules_grommet_es6_components_DataTableColumns_DataTableColumns_js.chunk.js:467:7
    at http://localhost:3000/static/js/bundle.js:267287:25
    at onCheckBoxChange (http://localhost:3000/static/js/bundle.js:261478:5)
    at onChange (http://localhost:3000/static/js/bundle.js:261525:16)
    at onChange (http://localhost:3000/static/js/bundle.js:261148:22)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:407356:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:407400:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:407455:35)
    at invokeGuardedCallbackAndCatchFirstError (http://localhost:3000/static/js/bundle.js:407469:29)
    at executeDispatch (http://localhost:3000/static/js/bundle.js:411091:7)
ERROR
onView is not a function
TypeError: onView is not a function
    at http://localhost:3000/static/js/vendors-node_modules_grommet_es6_components_DataTableColumns_DataTableColumns_js.chunk.js:467:7
    at http://localhost:3000/static/js/bundle.js:267287:25
    at onCheckBoxChange (http://localhost:3000/static/js/bundle.js:261478:5)
    at onChange (http://localhost:3000/static/js/bundle.js:261525:16)
    at onChange (http://localhost:3000/static/js/bundle.js:261148:22)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:407356:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:407400:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:407455:35)
    at invokeGuardedCallbackAndCatchFirstError (http://localhost:3000/static/js/bundle.js:407469:29)
    at executeDispatch (http://localhost:3000/static/js/bundle.js:411091:7)```
<!--
  -- Here's a Codesandbox template that serves as a nice starting point
  -- for demonstrating an issue: https://codesandbox.io/s/m7mml8l0zj
  -->

### Steps to Reproduce

1. using DataTableColumns component with DataTable in the app  
2.clicking the mange columns button
3. either try to toggle a column or switch columns order
4. then the user will see the error

### Your Environment

<!--- Include as many relevant details about the environment you experienced the bug in -->

- Grommet version: v2.32.1
- Browser Name and version: Chrom v114
- Operating System and version (desktop or mobile): Desktop Mac

**Comment by jcfilben** [comment]
Hi @Lewiszhl can you try using the latest version of Grommet (v2.33.1) and see if you are still running into this issue?

**Comment by Lewiszhl** [comment]
> Hi @Lewiszhl can you try using the latest version of Grommet (v2.33.1) and see if you are still running into this issue?
Yes, I just tried, still get this issue.

**Comment by jcfilben** [comment]
Thanks for confirming you are still seeing this issue in the latest version of Grommet. I just tested with this storybook example: https://storybook.grommet.io/?path=/story/data-datatablecolumns-simple--simple and was able to toggle columns and reorder then without issue. Can you share a [codesandbox](https://codesandbox.io/s/m7mml8l0zj) with a minimal reproduction of the issue so we can uncover what the issue might be?

**Comment by Lewiszhl** [comment]
Temporarily close the issue, since found some custom components used in the project were not compatible with this feature.Thanks @jcfilben
