### ISSUE TITLE
React 18.3.1 w/ grommet useState fails 

### ISSUE THREAD

**Issue by Aubrey-Russell** [grommet/grommet#7228]
Updating to react 18.3.1 breaks grommetjs 

### Expected Behavior

It should work normally

### Actual Behavior

Uncaught TypeError: Cannot read properties of null (reading 'useState')
    at useState (react.development.js:1622:1)
    at Grommet.js:53:27
    at renderWithHooks (react-dom.development.js:15486:1)
    at updateForwardRef (react-dom.development.js:19245:1)
    at beginWork (react-dom.development.js:21675:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27490:1)
    at performUnitOfWork (react-dom.development.js:26596:1)

### URL, screen shot, or Codepen exhibiting the issue

![image](https://github.com/grommet/grommet/assets/157523547/3448f649-7b65-4e96-b8a2-7bea282bae18)

### Steps to Reproduce

Install grommet 2.37.0 with react 18.3.1

### Your Environment

VS code react application with grommetjs

- Grommet version:     "grommet": "^2.37.0",
- Browser Name and version: edge
- Operating System and version (desktop or mobile): windows

**Comment by jcfilben** [comment]
I tried to reproduce the issue in [this codesandbox](https://codesandbox.io/p/sandbox/grommet-v2-template-forked-wwd2qq?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clph2dvjv00073b6ilcz65eoa%2522%252C%2522sizes%2522%253A%255Bnull%252Cnull%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clph2dvjv00033b6ieyvjao8u%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clph2dvjv00043b6i3fv14pdp%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clph2dvjv00063b6iifo148ip%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clph2dvjv00033b6ieyvjao8u%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clph2dvju00023b6ih3gw98dq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clph2dvjv00033b6ieyvjao8u%2522%252C%2522activeTabId%2522%253A%2522clph2dvju00023b6ih3gw98dq%2522%257D%252C%2522clph2dvjv00063b6iifo148ip%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clph2dvjv00053b6i5qxizh1l%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clph2dvjv00063b6iifo148ip%2522%252C%2522activeTabId%2522%253A%2522clph2dvjv00053b6i5qxizh1l%2522%257D%252C%2522clph2dvjv00043b6i3fv14pdp%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clph2dvjv00043b6i3fv14pdp%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) but wasn't getting an error. Let me know if there is anything I should adjust in my codesandbox to be able to reproduce the issue.

**Comment by Aubrey-Russell** [comment]
@jcfilben thank you very much for checking, I am attempting to replicate it on my end on a fresh repo so I will post here if I am able to. We are running a complex micro front end environment so its possible something specific to our project is leading to an unexpected interaction. Thanks again!

**Comment by Aubrey-Russell** [comment]
Hi, I managed to replicate it here at this repo and will try to import into code sandbox as well:

https://github.com/Aubrey-Russell/grommet-react-mfe-issue-example

This is using nx nrwl as a framework for context:

![image](https://github.com/grommet/grommet/assets/157523547/10e204b4-142a-4c52-ab7d-a5f4a70ac0a9)

**Comment by jcfilben** [comment]
Thanks for putting together the sample repo, I cloned it and ran `nx serve mfe-ex-1` but didn't see any errors in the console. For more context I'm using pnpm v8.7.6. Also I haven't used nx before so not sure if I'm missing anything there or running things incorrectly

**Comment by Aubrey-Russell** [comment]
@jcfilben Hi, sorry I thought I had included instructions in the readme but I did not.

Please run pnpm nx serve shell. I have also created the issue in the nx nrwl repo .
