### ISSUE TITLE
Error while building with webpack

### ISSUE THREAD

**Issue by plasmashadow** [grommet/grommet#855]
Tried to run webpack with grommet. Encountered the below error

```
ERROR in ./~/grommet/~/markdown-to-jsx/~/remark/~/stringify-entities/~/character-entities-html4/index.json
Module parse failed: /Users/sathya/github/public/smashers/node_modules/grommet/node_modules/markdown-to-jsx/node_modules/remark/node_modules/stringify-entities/node_modules/character-entities-html4/index.json Unexpected token (2:8)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:8)
    at Parser.pp$4.raise (/Users/sathya/github/public/smashers/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/sathya/github/public/smashers/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/Users/sathya/github/public/smashers/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/Users/sathya/github/public/smashers/node_modules/webpack/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/Users/sathya/github/public/smashers/node_modules/webpack/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseBlock (/Users/sathya/github/public/smashers/node_modules/webpack/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$1.parseStatement (/Users/sathya/github/public/smashers/node_modules/webpack/node_modules/acorn/dist/acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (/Users/sathya/github/public/smashers/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Users/sathya/github/public/smashers/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Users/sathya/github/public/smashers/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Users/sathya/github/public/smashers/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/sathya/github/public/smashers/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/sathya/github/public/smashers/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/sathya/github/public/smashers/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/sathya/github/public/smashers/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/sathya/github/public/smashers/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
 @ ./~/grommet/~/markdown-to-jsx/~/remark/~/stringify-entities/~/character-entities-html4/index.js 12:17-40
```

And my webpack configuration is below
```
{
    entry: APP_PATH+"/app.react.js",
    resolve: {
        extensions: ["", ".js", ".jsx"]
    },
    output: {
        path: BUILD_PATH,
        filename: "static/app_bundle.js"
    },
    module: {
        loaders: [
            {
                test: /\.css$/,
                loaders: ["style", "css"],
                include: APP_PATH
            },
            {
                test: /\.js?$/,
                loaders: ["babel"],
                include: APP_PATH
            },
            {
              test: /\.json$/,
              loaders: "json",
              include: APP_PATH
            }
        ]
    }
}
```

Since there is a json loader to parse json files. It should not cause this problem but i wonder why this is happening.

I can't figure out the problem. Is there something wrong with my webpack configuration ?

**Comment by alansouzati** [comment]
Can you try the `grommet-standalone` project?

https://github.com/grommet/grommet-standalone

We provide a sample webpack config to work with Grommet.

I'm not sure why you are facing issue with a json loader, but I don't think we require one.

It would be great if you can try to reproduce the issue using the grommet-standalone.

**Comment by alansouzati** [comment]
hey @plasmashadow any updates here?

**Comment by plasmashadow** [comment]
When i changed the webpack config file to below code it started working.
```
var viewer = {
    entry: APP_PATH+"/app.react.js",
    resolve: {
        extensions: ["", ".js", ".jsx"]
    },
    output: {
        path: BUILD_PATH,
        filename: env ? "static/app_bundle.min.js" :"static/app_bundle.js"
    },
    module: {
        loaders: [
            {
                test: /\.css$/,
                loaders: ["style", "css"],
                include: APP_PATH
            },
            {
                test: /\.js?$/,
                loaders: ["babel"],
                include: APP_PATH
            },
            {
              test: /\.json$/,
              loaders: ["json"]
            }
        ]
    }
};
```

**Comment by bryanjacquot** [comment]
Good to hear, thanks.
