### ISSUE TITLE
Getting Started page on grommet.io is lacking

### ISSUE THREAD

**Issue by billbr** [grommet/grommet#90]
I am trying to follow the getting started page and have found several challenges. 
I have found the following on Debian 8:
1. When following the instructions, "node" is not found, which is required for grommet.  I found that creating a symbolic link for node pointing to /usr/bin/nodejs makes grommet seem to work.
2. 'grommet init sample-app' must have permission to write the sample app. In my case this requires root privileges.
3. The getting started page should set an expectation of how much stuff will be loaded into the system. For my system it was 236MB.

Perhaps a troubleshooting link on the getting started page would resolve os or environment specific challenges.

**Comment by ieugen** [comment]
+1 for the things above. 
```
 grommet init sample-app
Could not find Grommet!
```

**Comment by bryanjacquot** [comment]
Thanks for the feedback.  We will refine these instructions.  If you follow the button that says "Start Project", you'll see there are a few steps required when setting up your first project to get the dependencies in place.

http://grommet.io/docs/develop/get-started

**Comment by ieugen** [comment]
I did that.

**Comment by alansouzati** [comment]
Hi @ieugen, could you please confirm the path where your global packages get's installed?

Personally, I haven't tested Grommet on top of io.js.

**Comment by ieugen** [comment]
Hi, 

I've been using this setup for a few months and I had no other problems: 

```
ls -la ~/.nvm/versions/io.js/v2.2.1/lib/node_modules/grommet/
total 800
drwxr-xr-x 1 ieugen ieugen    584 aug 17 15:36 .
drwxr-xr-x 1 ieugen ieugen    512 aug 17 15:37 ..
drwxr-xr-x 1 ieugen ieugen     50 aug 17 15:35 actions
drwxr-xr-x 1 ieugen ieugen     20 iul 28 06:25 bin
drwxr-xr-x 1 ieugen ieugen   1012 aug 17 15:35 components
drwxr-xr-x 1 ieugen ieugen    154 aug 17 15:35 examples
-rw-r--r-- 1 ieugen ieugen 105101 iul 28 06:25 grommet-hpe.min.css
-rw-r--r-- 1 ieugen ieugen 102880 iul 28 06:25 grommet-hpinc.min.css
-rw-r--r-- 1 ieugen ieugen 104523 iul 28 06:25 grommet.min.css
-rw-r--r-- 1 ieugen ieugen 448373 iul 28 06:26 grommet.min.js
-rw-r--r-- 1 ieugen ieugen   1604 iul 28 06:25 grommet.svg
-rwxr-xr-x 1 ieugen ieugen   7291 iul 28 06:25 hpesm_sec_blk_pos_rgb.svg
-rwxr-xr-x 1 ieugen ieugen   7477 iul 28 06:25 hpesm_sec_grn_pos_rgb.svg
-rw-r--r-- 1 ieugen ieugen   3463 iul 28 06:25 index.js
drwxr-xr-x 1 ieugen ieugen     32 aug 17 15:35 messages
drwxr-xr-x 1 ieugen ieugen    186 aug 17 15:35 mixins
-rwxr-xr-x 1 ieugen ieugen   6553 iul 28 06:25 mobile-app-icon.png
-rw-r--r-- 1 ieugen ieugen   2114 iul 28 06:25 mobile-app-icon.svg
drwxr-xr-x 1 ieugen ieugen    726 aug 17 15:36 node_modules
-rw-r--r-- 1 ieugen ieugen   3663 aug 17 15:35 package.json
-rw-r--r-- 1 ieugen ieugen   1723 iul 28 06:25 README.md
drwxr-xr-x 1 ieugen ieugen     40 aug 17 15:35 scss
-rwxr-xr-x 1 ieugen ieugen    662 iul 28 06:25 shortcut-icon.png
drwxr-xr-x 1 ieugen ieugen     56 aug 17 15:35 stores
drwxr-xr-x 1 ieugen ieugen    124 aug 17 15:35 templates
drwxr-xr-x 1 ieugen ieugen    266 aug 17 15:35 utils
```

**Comment by alansouzati** [comment]
I understand, I'm sorry about that. There is where we look for possible installed version of Grommet:

```
NODE_PATH
/usr/lib/node_modules
/usr/local/lib/node_modules
```

Where NODE_PATH takes priority over the others. Can you confirm what is set in your NODE_PATH?

If it is not `.nvm/versions/io.js/v2.2.1/lib/node_modules/grommet/` can you set that?

**Comment by ieugen** [comment]
Hi, 

I've ran the following: 
```
$ NODE_PATH=~/.nvm/versions/io.js/v2.2.1/lib/node_modules grommet init xxa
```
This creates the project, however, it builds a lot of native libraries while building the process. This should not happen while creating a sample project.  

The result however is not very usable:
```
$ npm install
$ gulp dev
[10:16:42] Using gulpfile ~/contracte/gpec-event/xxa/gulpfile.js
[10:16:42] Starting 'dev-preprocess'...
[10:16:42] Starting 'preprocess'...
[10:16:42] Starting 'clean'...
[10:16:42] Finished 'clean' after 2.99 ms
[10:16:42] Starting 'copy'...
[10:16:42] Finished 'copy' after 12 ms
[10:16:42] Starting 'jslint'...

events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: Definition for rule 'react/jsx-max-props-per-line' was not found.
    at /home/ieugen/contracte/gpec-event/xxa/node_modules/eslint/lib/eslint.js:647:27
    at Array.forEach (native)
    at EventEmitter.module.exports.api.verify (/home/ieugen/contracte/gpec-event/xxa/node_modules/eslint/lib/eslint.js:620:16)
    at verify (/home/ieugen/contracte/gpec-event/xxa/node_modules/gulp-eslint/index.js:21:25)
    at DestroyableTransform._transform (/home/ieugen/contracte/gpec-event/xxa/node_modules/gulp-eslint/index.js:44:18)
    at DestroyableTransform.Transform._read (/home/ieugen/contracte/gpec-event/xxa/node_modules/gulp-eslint/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/home/ieugen/contracte/gpec-event/xxa/node_modules/gulp-eslint/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/home/ieugen/contracte/gpec-event/xxa/node_modules/gulp-eslint/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/home/ieugen/contracte/gpec-event/xxa/node_modules/gulp-eslint/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/home/ieugen/contracte/gpec-event/xxa/node_modules/gulp-eslint/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
```

Regards,

**Comment by bryanjacquot** [comment]
Believe it or not, this is progress.  You've now hit a defect that we fixed with the latest release of Grommet.  Can you run the following command to pickup the latest version?

**As admin or using sudo:**
```
$ npm update -g grommet
$ grommet init sample-app
$ cd sample-app
$ gulp dev
```

**Comment by ieugen** [comment]
Yes. it works now. The node path is still needed. So far grommet is the only app that needs this. I've added 
https://github.com/HewlettPackard/grommet/pull/166 to give more information about the issue.

**Comment by bryanjacquot** [comment]
Fixed in https://github.com/grommet/grommet/pull/166
